### ISSUE TITLE
No longer works after updating to 52.0 (64-bit) on Ubuntu 14.04  

### ISSUE THREAD

**Issue by stanwmusic** [fligtar/password-exporter#70] opened 2017-03-09 11:59 UTC
I just  let I Firefox update    and then all my saved passwords were gone! :(
 I managed to export the ones I had in Chrome browser  then  when I went to import them into Firefox, I find that password exporter no longer works!
I have  removed and reinstalled it  twice to no avail, it is installed but when  I click the  import button NOTHING happens.
 I had  over 700 saved passwords   in Firefox  before the  latest update to Firefox version  52.0 (64-bit).

**Comment by jvillalobos** [comment] 2017-03-11 20:54
Closing as duplicate of #68

**Closed as completed by jvillalobos** 2017-03-11 20:54 UTC
