### ISSUE TITLE
Doesn't work in Nightly 53.0a1 2016-11-23

### ISSUE THREAD

**Issue by Keith94** [fligtar/password-exporter#62] opened 2016-11-24 03:57 UTC
If you try to export passwords it pops up a small blank window, and the following errors are logged:

`SyntaxError: missing ( after for  pwdex-loginmanager.js:396:28`
`ReferenceError: srGetStrBundle is not defined[Learn More]  pwdex-global.js:30:9`

**Comment by Keith94** [comment] 2016-11-24 04:24
Actually, seems to be a conflict with "Keybinder" add-on. However, "export" and "import" buttons still don't do anything with Keybinder disabled..

`TypeError: passwordExporter.import is null[Learn More]  pwdexDialog.xul:1:1`
`TypeError: passwordExporter.export is null[Learn More]  pwdexDialog.xul:1:1`

**Comment by jvillalobos** [comment] 2017-03-11 20:56
Closing as duplicate of #68

**Closed as completed by jvillalobos** 2017-03-11 20:56 UTC
