### ISSUE TITLE
Not working with Firefox 52.0 (64-bit) MACOS 10.10.5

### ISSUE THREAD

**Issue by Catalpha** [fligtar/password-exporter#72] opened 2017-03-10 14:28 UTC
Not working with Firefox 52.0 MACOS 10.10.5

**Comment by giampi75** [comment] 2017-03-11 16:11
I confirm 52.0 Windows 10

**Comment by jvillalobos** [comment] 2017-03-11 20:55
Closing as duplicate of #68

**Closed as completed by jvillalobos** 2017-03-11 20:55 UTC
