### ISSUE TITLE
works great in regular Firefox but not at all in developer's version 530a2

### ISSUE THREAD

**Issue by brasscupcakes** [fligtar/password-exporter#69] opened 2017-03-04 22:20 UTC
Hi there - thanks for this great extension. Although it works fine on my regular ff installation, it does not work on the ff developer's installation at all. I tried updating to 530a2 and also rolling back to a couple of previous versions. Nothing happens when I click on export, even if I choose obfuscate. 
(this isn't pressing at all for me if there isn't an existing fix and nobody else is requesting. Easy enough to sync my firefox versions.). 
Best wishes!

**Comment by jvillalobos** [comment] 2017-03-11 20:54
Closing as duplicate of #68

**Closed as completed by jvillalobos** 2017-03-11 20:54 UTC
