### ISSUE TITLE
Not Working in Firefox 52 on Windows 10

### ISSUE THREAD

**Issue by MSB1230** [fligtar/password-exporter#71] opened 2017-03-09 14:54 UTC
I just installed Firefox 52 on a new Windows 10 machine and added this fine FF add-on.  My passwords were imported from another machine and the "Import Passwords" button doesn't do anything.

In fact, none of the buttons do anything in FF 52.  They are not disabled (greyed out), the simply do nothing.

**Comment by XLNT1** [comment] 2017-03-09 18:52
I'm having the same issue on a computer I reinstalled Windows 10 on. P.E. worked w/o any issues before, I used the same version (52.0) of Firefox. I also tried the debug link posted by Mr Scott, wasn't able to pull it up.

**Comment by Modsojoy** [comment] 2017-03-09 20:37
Same here, just built a new PC, i need my passwords ffs

**Comment by Dalamar6** [comment] 2017-03-10 15:49
+1 not working.

Would also appreciate password-encrypted export/import. Can't be that hard to use something more secure than basic obfuscation.

**Comment by giampi75** [comment] 2017-03-11 16:12
I confirm

**Comment by Cabola** [comment] 2017-03-11 16:23
The reason why it's not working, well at least one of the reasons is because in the install.rdf the max FF version is set to 47.*. So any FF above version 47 won't work.

Last update (from v1.3.1.1 to v1.3.2) it was changed from maxversion 40.* to 47.*. Proof: https://addons.mozilla.org/en-US/firefox/files/compare/421261...317474/

**Comment by MSB1230** [comment] 2017-03-11 19:42
Can it be fixed without waiting for the author to re-post it ??

**Comment by jvillalobos** [comment] 2017-03-11 20:54
Closing as duplicate of #68

**Closed as completed by jvillalobos** 2017-03-11 20:54 UTC
